import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { configuration, launch, boot, environment, observeErrors, output, save, TOUCH_VIEWPORTS, touchContextOptions } from './browser-v2.mjs';

// Observer commands are real DOM/mouse/keyboard interactions. evaluate() reads
// state or projects world objects for mouse picking. Deterministic replay and
// natural group expiry invoke step(); Developed world is exercised by UI clicks.
const config = configuration();
let browser, page, activeHomeId='s0';
const report={at:new Date().toISOString(),url:config.url,tier:config.tier,quality:config.quality,scope:'Real DOM/mouse/keyboard observer commands, deterministic API only for replay and natural disappearance setup',checks:[],errors:[],warnings:[],screenshots:[],responsive:[]};
const button=(action,value)=>page.locator(`[data-action="${action}"]${value===undefined?'':`[data-value="${value}"]`}`);
const state=()=>page.evaluate(()=>({tick:littleworld.state.tick,step:littleworld.state.step,time:littleworld.state.time,seed:littleworld.state.seed,view:{...littleworld.view}}));
const settle=()=>page.waitForTimeout(500);
// Software WebGL may take longer than a second to produce a frame. Wait for
// the observable clock transition; keep the same progress assertions below.
const waitForProgress=step=>page.waitForFunction(before=>littleworld.state.step>before,step,{timeout:30000});
async function check(name,fn){try{const detail=await fn();report.checks.push({name,status:'passed',detail});console.log(`PASS ${name}`);}catch(error){report.checks.push({name,status:'failed',error:error.stack});console.log(`FAIL ${name}: ${error.message}`);try{await shot(`failure-${report.checks.length}`);}catch{}}report.passed=report.checks.filter(c=>c.status==='passed').length;report.failed=report.checks.filter(c=>c.status==='failed').length;await save(config,'controls-v2-report.json',{...report,status:'in-progress'});}
async function pause(){if(!(await state()).view.paused)await button('pause').click();await settle();}
async function settings(){if(!await page.locator('#atlas-settings').isVisible())await button('settings').click();}
async function reset(seed,civCount=config.civCount){await pause();await settings();await page.locator('#atlas-seed').fill(seed);await page.locator('#atlas-civs').fill(String(civCount));await page.locator('.seed-form button[type="submit"]').click();await settle();}
async function select(id){await page.locator(`.faction-list [data-value="${id}"]`).click();await settle();}
async function shot(name){const path=output(config,`controls-v2-${name}.png`);await page.screenshot({path,timeout:60000});report.screenshots.push({path,...await page.evaluate(()=>({tick:littleworld.state.tick,seed:littleworld.state.seed,viewport:{width:innerWidth,height:innerHeight},camera:littleworld.camera.position.toArray(),target:littleworld.controls.target.toArray(),diagnostics:littleworld.diagnostics}))});}
async function populationEvidence(){return page.evaluate(()=>{const d=littleworld.diagnostics;let actualInstances=0;const meshes=[];littleworld.scene.traverse(o=>{if(o.isInstancedMesh&&o.geometry?.attributes?.crowdMotion){actualInstances+=o.count;meshes.push({name:o.name,count:o.count,visible:o.visible});}});return {total:littleworld.state.settlements.reduce((n,s)=>n+s.population,0),diagnostics:d,actualInstances,meshes,scale:document.querySelector('[data-slot="world-scale"]').innerText};});}
async function mobileControls() {
  const desktop = page;
  for (const viewport of TOUCH_VIEWPORTS) {
    const context = await browser.newContext(touchContextOptions(viewport));
    try {
      page = await context.newPage(); page.setDefaultTimeout(20000); observeErrors(page, report);
      await boot(page, config); await settle();
      await check(`Touch ${viewport.name}: coarse-pointer layout starts collapsed and contains its canvas`, async () => {
        const facts = await page.evaluate(() => { const canvas = document.querySelector('#app canvas').getBoundingClientRect(); return { coarse: matchMedia('(pointer: coarse)').matches, touchPoints: navigator.maxTouchPoints, width: innerWidth, height: innerHeight, documentWidth: document.documentElement.scrollWidth, documentHeight: document.documentElement.scrollHeight, canvas: { x: canvas.x, y: canvas.y, right: canvas.right, bottom: canvas.bottom } }; });
        assert.equal(facts.coarse, true); assert.ok(facts.touchPoints > 0);
        assert.equal(facts.width, viewport.width); assert.equal(facts.height, viewport.height);
        assert.ok(facts.documentWidth <= facts.width && facts.documentHeight <= facts.height);
        assert.ok(facts.canvas.x >= 0 && facts.canvas.y >= 0 && facts.canvas.right <= facts.width + 1 && facts.canvas.bottom <= facts.height + 1);
        assert.equal(await page.locator('.mobile-toolbar').isVisible(), true);
        for (const selector of ['.faction-index', '.inspector', '.world-chronicle', '.observation-tools']) assert.equal(await page.locator(selector).isVisible(), false, `${selector} should start collapsed`);
        report.responsive.push({ device: viewport.name, hasTouch: true, isMobile: true, ...facts }); return facts;
      });
      await shot(`touch-${viewport.name}-collapsed`);
      await check(`Touch ${viewport.name}: society and inspector panels open, fit and close`, async () => {
        for (const [value, selector] of [['factions', '#atlas-inhabitants'], ['inspector', '#atlas-inspector']]) {
          await button('mobile-panel', value).tap(); const panel = page.locator(selector); assert.equal(await panel.isVisible(), true);
          const box = await panel.boundingBox(); assert.ok(box.x >= 0 && box.y >= 0 && box.x + box.width <= viewport.width + 1 && box.y + box.height <= viewport.height + 1);
          await panel.locator('[data-action="close-mobile-panel"]').tap(); assert.equal(await panel.isVisible(), false);
        }
      });
      await check(`Touch ${viewport.name}: one-finger pan, pinch zoom and two-finger orbit keep the page stationary`, async () => {
        const client = await context.newCDPSession(page);
        const camera = () => page.evaluate(() => ({ position: littleworld.camera.position.toArray(), target: littleworld.controls.target.toArray(), distance: littleworld.camera.position.distanceTo(littleworld.controls.target), selected: littleworld.view.selectedId, step: littleworld.state.step, scroll: [scrollX, scrollY] }));
        const center = { x: viewport.width / 2, y: viewport.height / 2 };
        assert.equal(await page.evaluate(p => document.elementFromPoint(p.x, p.y)?.tagName, center), 'CANVAS');
        const dispatch = (type, points) => client.send('Input.dispatchTouchEvent', { type, touchPoints: points.map((p, i) => ({ id: i + 1, x: p.x, y: p.y, radiusX: 6, radiusY: 6, force: 1 })) });
        const gesture = async (from, to) => { await dispatch('touchStart', from); for (let i = 1; i <= 8; i++) { await dispatch('touchMove', from.map((p, j) => ({ x: p.x + (to[j].x - p.x) * i / 8, y: p.y + (to[j].y - p.y) * i / 8 }))); await page.waitForTimeout(25); } await dispatch('touchEnd', []); await settle(); };
        const before = await camera();
        await gesture([center], [{ x: center.x + 45, y: center.y + 20 }]);
        const panned = await camera(); assert.ok(Math.hypot(...panned.target.map((v, i) => v - before.target[i])) > .01, 'one-finger touch did not pan');
        const pair = [{ x: center.x - 30, y: center.y }, { x: center.x + 30, y: center.y }];
        await gesture(pair, [{ x: center.x - 65, y: center.y }, { x: center.x + 65, y: center.y }]);
        const zoomed = await camera(); assert.ok(zoomed.distance < panned.distance - .01, 'pinch spread did not zoom in');
        await gesture(pair, pair.map(p => ({ x: p.x + 35, y: p.y + 15 })));
        const orbited = await camera(); assert.notDeepEqual(orbited.position, zoomed.position, 'two-finger drag did not orbit');
        for (const sample of [panned, zoomed, orbited]) { assert.equal(sample.selected, before.selected, 'gesture produced a spurious selection'); assert.equal(sample.step, before.step, 'paused touch interaction advanced simulation'); assert.deepEqual(sample.scroll, [0, 0], 'touch gesture scrolled the page'); }
        await client.detach(); return { before, panned, zoomed, orbited };
      });
      await shot(`touch-${viewport.name}-after-gestures`);
    } finally { await context.close(); page = desktop; }
  }
}
await mkdir(config.outputDir,{recursive:true});
try{
  browser=await launch(config);page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});page.setDefaultTimeout(20000);observeErrors(page,report);
  await boot(page,config);report.environment=await environment(page,browser,config);await pause();
  await check('Boot: configured faction controls, WebGL canvas, current cycle labels',async()=>{assert.equal(await page.locator('.faction-entry').count(),config.civCount);assert.equal(await page.locator('#app canvas').count(),1);assert.match(await page.locator('.world-date').innerText(),/World cycle/i);assert.doesNotMatch(await page.locator('#ui').innerText(),/\bday(?:s)?\b/i);assert.equal((await state()).view.speed,2,'default observation speed is2x');return page.evaluate(()=>{const gl=littleworld.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),initialPopulation:littleworld.diagnostics.totalPopulation};});});
  await check('Pause button freezes cycles, pulses, and sampled individual motion',async()=>{const a=await state();const motion=await page.evaluate(()=>littleworld.getMotionSamples());await page.waitForTimeout(1100);const b=await state();assert.equal(b.step,a.step);assert.equal(b.time,a.time);assert.deepEqual(await page.evaluate(()=>littleworld.getMotionSamples()),motion);assert.equal(await button('pause').getAttribute('aria-label'),'Resume simulation');return {step:b.step,samples:motion.length};});
  await check('Resume button advances simulation pulses',async()=>{const a=await state();await button('pause').click();await waitForProgress(a.step);assert.ok((await state()).step>a.step);await pause();});
  for(const speed of [1,2,4,16,32])await check(`${speed}x button sets speed, resumes, and advances cycles`,async()=>{await button('speed',speed).click();const a=await state();assert.equal(a.view.speed,speed);assert.equal(a.view.paused,false);assert.equal(await button('speed',speed).getAttribute('aria-pressed'),'true');await waitForProgress(a.step);const b=await state();assert.ok(b.step>a.step);await pause();return {pulses:b.step-a.step,cycles:b.time-a.time};});
  await check('Space toggles pause; number shortcuts choose all five rates',async()=>{await page.mouse.click(720,600);await page.keyboard.press('Space');assert.equal((await state()).view.paused,false);await page.keyboard.press('Space');assert.equal((await state()).view.paused,true);for(const [key,speed]of [['1',1],['2',2],['3',4],['4',16],['5',32]]){await page.keyboard.press(key);assert.equal((await state()).view.speed,speed);}await pause();});
  await reset('first-light');
  await check('Seed form resets to cycle zero and clears selection follow',async()=>{const s=await state();assert.equal(s.seed,'first-light');assert.equal(s.tick,0);assert.equal(s.step,0);assert.equal(s.view.selectedId,'s0');assert.equal(s.view.followId,null);});
  await check('Civilization slider starts reproducible three, four and five civilization worlds',async()=>{for(const civCount of [3,4,5]){await reset('controls-civ-count',civCount);assert.equal(await page.evaluate(()=>littleworld.state.factions.length),civCount);assert.equal(await page.locator('.faction-entry').count(),civCount);const initial=await page.evaluate(()=>JSON.stringify(littleworld.state));await reset('controls-civ-count',civCount);assert.equal(await page.evaluate(()=>JSON.stringify(littleworld.state)),initial);}await reset('first-light');return {counts:[3,4,5]};});
  await check('Unsaved seed and civilization edits survive blur and interface refresh',async()=>{await settings();await page.locator('#atlas-seed').fill('pending-seed-edit');await page.locator('#atlas-civs').fill('5');await page.locator('#atlas-quality').focus();await page.waitForTimeout(1200);assert.equal(await page.locator('#atlas-seed').inputValue(),'pending-seed-edit');assert.equal(await page.locator('#atlas-civs').inputValue(),'5');await page.locator('.seed-form button[type="submit"]').click();await settle();assert.equal((await state()).seed,'pending-seed-edit');assert.equal(await page.evaluate(()=>littleworld.state.factions.length),5);await reset('first-light');});
  await check('Faction perspective hides unknown actors and switching views never changes simulation',async()=>{await settings();const before=await page.evaluate(()=>JSON.stringify(littleworld.state));const factionIds=await page.evaluate(()=>littleworld.state.factions.map(f=>f.id));for(const id of factionIds){await page.locator('#atlas-perspective').selectOption(id);await settle();assert.equal((await state()).view.perspective,id);const shown=await page.evaluate(()=>({viewer:littleworld.shownState.viewer,ids:littleworld.shownState.settlements.map(s=>s.id),factions:littleworld.shownState.factions.map(f=>({id:f.id,economy:f.economy}))}));assert.equal(shown.viewer.factionId,id);assert.ok(shown.ids.length>=1);for(const f of shown.factions)if(f.id!==id)assert.equal(f.economy.population,null);assert.equal(await page.evaluate(()=>JSON.stringify(littleworld.state)),before);}await page.locator('#atlas-perspective').selectOption('omniscient');await settle();assert.equal((await state()).view.perspective,'omniscient');assert.equal(await page.locator('.faction-entry').count(),config.civCount);assert.equal(await page.evaluate(()=>JSON.stringify(littleworld.state)),before);});
  await check('Seed input protects text from global keyboard shortcuts',async()=>{await settings();const a=await state();await page.locator('#atlas-seed').fill('');await page.locator('#atlas-seed').pressSequentially('1 2 3 4 f c h');const b=await state();assert.equal(b.view.speed,a.view.speed);assert.equal(b.view.paused,a.view.paused);assert.equal(b.view.cinematic,a.view.cinematic);assert.equal(await page.locator('#atlas-seed').inputValue(),'1 2 3 4 f c h');await page.keyboard.press('Escape');});
  await check('Reset same seed reproduces identical initial state and 30-cycle replay',async()=>{await reset('controls-determinism');const a=await page.evaluate(()=>JSON.stringify(littleworld.state));await page.evaluate(()=>littleworld.step(30));const b=await page.evaluate(()=>JSON.stringify(littleworld.state));await reset('controls-determinism');assert.equal(await page.evaluate(()=>JSON.stringify(littleworld.state)),a);await page.evaluate(()=>littleworld.step(30));assert.equal(await page.evaluate(()=>JSON.stringify(littleworld.state)),b);return {initialBytes:a.length,replayBytes:b.length};});
  await reset('first-light');
  for(let i=0;i<config.civCount;i++)await check(`Faction ${i+1} click selects actual colony`,async()=>{await select(`s${i}`);assert.equal((await state()).view.selectedId,`s${i}`);assert.equal(await page.locator(`.faction-list [data-value="s${i}"]`).getAttribute('aria-pressed'),'true');return page.locator('.selection-header').innerText();});
  await check('Visible world label selects the named settlement',async()=>{let clicked=false;const labels=page.locator('.world-label');for(let i=0;i<await labels.count();i++){const label=labels.nth(i);if(!await label.isVisible())continue;try{await label.click({trial:true,timeout:5000});}catch{continue;}const name=await label.innerText();await label.click();const id=await page.evaluate(name=>littleworld.state.settlements.find(s=>s.name===name)?.id,name);assert.equal((await state()).view.selectedId,id);clicked=true;break;}assert.ok(clicked,'No unobscured world label available');});
  await check('Follow button focuses colony and toggles off',async()=>{await select('s0');const a=await page.evaluate(()=>littleworld.camera.position.toArray());await button('follow').click();await page.waitForTimeout(1000);assert.equal((await state()).view.followId,'s0');assert.equal(await button('follow').getAttribute('aria-pressed'),'true');assert.notDeepEqual(await page.evaluate(()=>littleworld.camera.position.toArray()),a);await button('follow').click();assert.equal((await state()).view.followId,null);});
  await check('World drag cancels follow',async()=>{await button('follow').click();await settle();await page.mouse.move(650,450);await page.mouse.down();await page.mouse.move(735,430,{steps:7});await page.mouse.up();assert.equal((await state()).view.followId,null);});
  await check('Cinematic button moves paused camera; Escape exits',async()=>{await button('cinematic').click();const a=await page.evaluate(()=>littleworld.camera.position.toArray());await page.waitForTimeout(1000);assert.equal((await state()).view.cinematic,true);assert.notDeepEqual(await page.evaluate(()=>littleworld.camera.position.toArray()),a);await page.keyboard.press('Escape');await settle();assert.equal((await state()).view.cinematic,false);assert.equal((await state()).view.followId,null);});
  await check('Keyboard F/C/H follow, cinematic and UI visibility controls work',async()=>{await page.mouse.click(720,600);await page.keyboard.press('f');assert.equal((await state()).view.followId,(await state()).view.selectedId);await page.keyboard.press('c');assert.equal((await state()).view.cinematic,true);await page.keyboard.press('c');assert.equal((await state()).view.cinematic,false);await page.keyboard.press('h');assert.equal(await page.locator('#ui').isVisible(),false);await page.keyboard.press('h');assert.equal(await page.locator('#ui').isVisible(),true);await page.keyboard.press('Escape');});
  await check('Settings quality switches real renderer shadows',async()=>{await settings();assert.equal(await button('settings').getAttribute('aria-expanded'),'true');await page.locator('#atlas-quality').selectOption('low');assert.equal((await state()).view.quality,'low');assert.equal(await page.evaluate(()=>littleworld.renderer.shadowMap.enabled),false);await page.locator('#atlas-quality').selectOption('high');assert.equal((await state()).view.quality,'high');assert.equal(await page.evaluate(()=>littleworld.renderer.shadowMap.enabled),true);await page.locator('#atlas-quality').selectOption(config.quality);});
  await check('Field guide opens and explains actual individuals and cycle time',async()=>{await page.locator('.render-reading [data-action="help"]').click();assert.ok(await page.locator('.field-guide').isVisible());assert.equal(await page.locator('#atlas-settings').isVisible(),false);const guide=await page.locator('.field-guide').innerText();assert.match(guide,/actual individual/i);assert.match(guide,/cycle is one simulation second/i);await page.locator('.guide-close').click();assert.equal(await page.locator('.field-guide').isVisible(),false);});
  await check('Focused buttons retain native Space and Enter activation',async()=>{await pause();if(await page.locator('#atlas-settings').isVisible())await button('settings').click();await button('settings').focus();await page.keyboard.press('Space');assert.equal(await page.locator('#atlas-settings').isVisible(),true);assert.equal((await state()).view.paused,true);await button('settings').click();await button('pause').focus();await page.keyboard.press('Enter');assert.equal((await state()).view.paused,false);await page.keyboard.press('Enter');assert.equal((await state()).view.paused,true);});
  await check('Settings and field guide exclude each other and dismiss cleanly',async()=>{await settings();await page.locator('.render-reading [data-action="help"]').click();assert.equal(await page.locator('.field-guide').isVisible(),true);assert.equal(await page.locator('#atlas-settings').isVisible(),false);assert.equal(await button('settings').getAttribute('aria-expanded'),'false');await button('settings').click();assert.equal(await page.locator('#atlas-settings').isVisible(),true);assert.equal(await page.locator('.field-guide').isVisible(),false);await button('settings').click();});
  await check('Repeated seed submissions use the latest seed and clear old follow',async()=>{await select('s0');await button('follow').click();await reset('controls-old');await reset('controls-new');const a=await state();assert.equal(a.seed,'controls-new');assert.equal(a.step,0);assert.equal(a.view.followId,null);await page.waitForTimeout(700);assert.equal((await state()).step,0);});
  await check('Reset interrupts Developed world without advancing the new seed or false success',async()=>{await reset('controls-interrupted');await button('develop').click();assert.equal(await button('develop').isEnabled(),false);await settings();await page.locator('#atlas-seed').fill('controls-latest');await page.locator('.seed-form button[type="submit"]').click();await settle();const a=await state();assert.equal(a.seed,'controls-latest');assert.equal(a.step,0);assert.equal(a.view.advancing,null);assert.equal(a.view.paused,true);await page.waitForTimeout(800);assert.equal((await state()).step,0);assert.equal(await button('develop').isEnabled(),true);assert.equal(await button('develop').getAttribute('aria-busy'),'false');assert.doesNotMatch(await page.locator('.ui-toast').innerText(),/1,200 cycles simulated/);return {seed:a.seed,step:a.step};});
  await check('Stop interrupts bulk advance, reports actual progress and stays paused',async()=>{await reset('controls-stop-bulk');const before=await state();await button('develop').click();await page.waitForFunction(()=>littleworld.view.advancing&&littleworld.view.advancing.done>0);assert.equal(await button('pause').getAttribute('aria-label'),'Stop advancing simulation');await button('pause').click();await page.waitForFunction(()=>littleworld.view.advancing===null);await page.waitForFunction(()=>!document.querySelector('[data-action="develop"]').disabled);const stopped=await state();assert.equal(stopped.view.paused,true);assert.ok(stopped.tick>before.tick&&stopped.tick-before.tick<1200);await page.waitForTimeout(900);assert.equal((await state()).step,stopped.step,'cancelled bulk job resumed later');assert.match(await page.locator('.ui-toast').innerText(),new RegExp(`stopped after ${(stopped.tick-before.tick).toLocaleString('en')} cycles`));return {completedCycles:stopped.tick-before.tick,step:stopped.step};});
  await check('Speed change cancels bulk advance and resumes only the requested clock rate',async()=>{await reset('controls-speed-cancel');await button('develop').click();await page.waitForFunction(()=>littleworld.view.advancing&&littleworld.view.advancing.done>0);await button('speed',4).click();await page.waitForFunction(()=>littleworld.view.advancing===null);const start=await state();assert.equal(start.view.paused,false);assert.equal(start.view.speed,4);await waitForProgress(start.step);const end=await state();assert.ok(end.step>start.step);assert.ok(end.tick-start.tick<25,'cancelled bulk job escaped as another25-cycle chunk');assert.equal(end.view.advancing,null);await pause();return {startStep:start.step,endStep:end.step,speed:end.view.speed};});
  await reset('first-light');await page.keyboard.press('Escape');await page.waitForTimeout(1700);await shot('initial-1440');
  await check('Developed world button actually advances current seed by 1,200 cycles',async()=>{const a=await state();const started=Date.now();await button('develop').click();assert.equal(await button('develop').isEnabled(),false);assert.equal(await button('develop').getAttribute('aria-busy'),'true');await page.keyboard.press('Enter');await page.keyboard.press('Enter');await page.keyboard.press('Enter');await page.waitForFunction(()=>littleworld.view.advancing===null&&littleworld.state.tick>=1200,{},{timeout:240000});await settle();const b=await state();assert.equal(b.seed,a.seed);assert.equal(b.tick-a.tick,1200);assert.equal(b.step-a.step,12000);assert.equal(b.view.paused,true);assert.equal(await button('develop').isEnabled(),true);assert.equal(await button('develop').getAttribute('aria-busy'),'false');assert.match(await page.locator('.ui-toast').innerText(),/1,200 cycles simulated/);return {milliseconds:Date.now()-started,cycle:b.tick};});
  if(await page.evaluate(()=>littleworld.state.outcome?.status==='victory'))await check('Natural domination pauses once; Keep watching resumes without repeated result interruption',async()=>{await page.waitForFunction(()=>littleworld.view.victoryObserved!==null&&littleworld.view.paused);assert.equal(await page.locator('.world-outcome').isVisible(),true);const result=await page.evaluate(()=>({...littleworld.state.outcome}));assert.ok(result.winnerId);await shot('natural-victory-result');await button('keep-watching').click();assert.equal((await state()).view.paused,false);assert.equal(await page.locator('.world-outcome').isVisible(),false);const step=(await state()).step;await waitForProgress(step);assert.ok((await state()).step>step);assert.equal((await state()).view.paused,false);assert.equal(await page.locator('.world-outcome').isVisible(),false);await pause();return {...result,continuedFromStep:step,continuedToStep:(await state()).step};});
  else report.checks.push({name:'Natural domination result controls',status:'not-observed',reason:'This natural seed did not reach victory during the Developed world interval; no synthetic winner was inserted.'});
  activeHomeId=await page.evaluate(()=>littleworld.state.settlements.find(h=>!h.occupiedBy&&littleworld.state.groups.some(g=>g.originId===h.id&&g.kind==='worker'))?.id||littleworld.state.settlements.find(h=>!h.occupiedBy&&h.population>0)?.id||'s0');
  await check('Developed world population equals represented and real visible mesh instances',async()=>{const e=await populationEvidence();report.populationEvidence=e;assert.equal(e.diagnostics.crowds.representedIndividuals,e.total);assert.equal(e.diagnostics.crowds.visibleIndividuals+e.diagnostics.crowds.culledIndividuals,e.total);assert.equal(e.actualInstances,e.diagnostics.crowds.visibleIndividuals);assert.equal(e.diagnostics.crowds.populationAccountingDelta,0);assert.match(e.scale,new RegExp(e.total.toLocaleString('en')));return {population:e.total,represented:e.diagnostics.crowds.representedIndividuals,visible:e.diagnostics.crowds.visibleIndividuals,actualMeshInstances:e.actualInstances};});
  await check('Population and visible counts in diagnostics settings are truthful',async()=>{await button('diagnostics').click();const e=await populationEvidence();const rows=await page.locator('.render-counts > div').evaluateAll(rows=>Object.fromEntries(rows.map(r=>[r.querySelector('dt').textContent,r.querySelector('dd').textContent])));assert.equal(rows['Actual population'],e.total.toLocaleString('en'));assert.equal(rows['Represented individuals'],e.diagnostics.crowds.representedIndividuals.toLocaleString('en'));assert.equal(rows['Visible in this view'],e.diagnostics.crowds.visibleIndividuals.toLocaleString('en'));await button('settings').click();return rows;});
  for(const mode of ['territory','knowledge','routes','resources','none'])await check(`${mode} overlay click updates view and accessible state`,async()=>{await button('overlay',mode).click();await settle();assert.equal((await state()).view.overlay,mode);assert.equal(await button('overlay',mode).getAttribute('aria-pressed'),'true');return page.evaluate(()=>({calls:littleworld.diagnostics.drawCalls,triangles:littleworld.diagnostics.triangles,groups:littleworld.state.groups.length}));});
  await shot('developed-1440');
  await check('Life, Intelligence, Record tabs update accessible panel',async()=>{for(const tab of ['intelligence','record','life']){await button('tab',tab).click();assert.equal(await button('tab',tab).getAttribute('aria-selected'),'true');assert.equal(await page.locator('[role="tabpanel"]').getAttribute('aria-labelledby'),`atlas-tab-${tab}`);assert.ok((await page.locator('[role="tabpanel"]').innerText()).length>30);}});
  await check('Inspector tabs support arrow, Home, and End keys',async()=>{await button('tab','life').focus();for(const[key,tab]of [['ArrowRight','intelligence'],['End','record'],['Home','life'],['ArrowLeft','record']]){await page.keyboard.press(key);assert.equal(await button('tab',tab).getAttribute('aria-selected'),'true');}await button('tab','life').click();});
  await check('Chronicle scope switches world and selected faction events',async()=>{await button('scope').click();assert.equal(await button('scope').innerText(),'Selected');await button('scope').click();assert.equal(await button('scope').innerText(),'All life');});
  await check('Visible party control selects and follows actual group',async()=>{await select(activeHomeId);await button('tab','life').click();const party=page.locator('.active-parties button').first();assert.ok(await party.count());const id=await party.getAttribute('data-value');await party.click();await settle();assert.equal((await state()).view.selectedId,id);assert.ok(await page.locator('.party-detail').isVisible());await button('follow').click();assert.equal((await state()).view.followId,id);await settle();await shot('party');await button('follow').click();return {id};});
  await check('Expired selected party falls back to its home and clears follow',async()=>{await select(activeHomeId);await button('tab','life').click();const party=page.locator('.active-parties button').first();assert.ok(await party.count());const id=await party.getAttribute('data-value');const origin=await page.evaluate(id=>littleworld.state.groups.find(g=>g.id===id)?.originId,id);await party.click();await settle();await button('follow').click();let cycles=0;while(cycles<360&&await page.evaluate(id=>littleworld.state.groups.some(g=>g.id===id),id)){await page.evaluate(()=>littleworld.step(5));cycles+=5;await page.waitForTimeout(20);}assert.equal(await page.evaluate(id=>littleworld.state.groups.some(g=>g.id===id),id),false,'Party did not naturally finish within 360 cycles');await page.waitForFunction(()=>littleworld.view.followId===null,null,{timeout:10000});await settle();assert.equal((await state()).view.selectedId,origin);assert.equal((await state()).view.followId,null);assert.equal(await page.locator('.party-detail').count(),0);return {expired:id,origin,cycles};});
  await check('Worksite link opens resource inspector and real remaining stock',async()=>{await select(activeHomeId);await button('tab','life').click();const site=page.locator('.site-links button').first();assert.ok(await site.count());const id=await site.getAttribute('data-value');await site.click();await settle();assert.equal((await state()).view.selectedId,id);assert.equal(await button('tab','life').innerText(),'Site');const node=await page.evaluate(id=>littleworld.state.nodes.find(n=>n.id===id),id);assert.match(await page.locator('.resource-introduction').innerText(),new RegExp(Math.round(node.amount).toLocaleString('en')));await button('follow').click();assert.equal((await state()).view.followId,id);await settle();await shot('resource');await button('follow').click();return {id,amount:node.amount};});
  await check('Resource Teams and Ledger tabs disclose actual teams and ledger values',async()=>{const id=(await state()).view.selectedId;const evidence=await page.evaluate(id=>{const node=littleworld.state.nodes.find(n=>n.id===id);return {teams:littleworld.state.groups.filter(g=>g.kind==='worker'&&g.targetId===id).length,ledger:littleworld.state.resourceLedger[node.kind]};},id);await button('tab','intelligence').click();assert.equal(await page.locator('.resource-teams > button').count(),evidence.teams);await button('tab','record').click();const dd=await page.locator('.ledger-list dd').allTextContents();assert.equal(dd[2],Math.round(evidence.ledger.extracted).toLocaleString('en'));assert.equal(dd[3],Math.round(evidence.ledger.delivered).toLocaleString('en'));await button('tab','life').click();return evidence;});
  await check('Canvas resource picking selects an actual visible deposit',async()=>{await page.keyboard.press('Escape');await page.waitForTimeout(1800);const points=await page.evaluate(async()=>{const {heightAt}=await import(new URL('./src/world.js',location.href).href);return littleworld.state.nodes.map(n=>{const p=littleworld.camera.position.clone().set(n.x,heightAt(n.x,n.z,littleworld.state.seed)+.4,n.z).project(littleworld.camera);const x=(p.x*.5+.5)*innerWidth,y=(-p.y*.5+.5)*innerHeight;return {id:n.id,x,y,z:p.z,clear:document.elementFromPoint(x,y)?.tagName==='CANVAS'};}).filter(p=>p.clear&&p.z<1&&p.x>220&&p.x<innerWidth-330&&p.y>100&&p.y<innerHeight-100).slice(0,16);});assert.ok(points.length);let result=null;for(const p of points){await page.mouse.click(p.x,p.y);await settle();const id=(await state()).view.selectedId;const node=await page.evaluate(id=>littleworld.state.nodes.find(n=>n.id===id),id);if(node){result={expected:p.id,selected:id,x:p.x,y:p.y};break;}}assert.ok(result,'All visible deposit canvas clicks failed to select any resource');return result;});
  await select(activeHomeId);await button('tab','life').click();await page.keyboard.press('Escape');await page.waitForTimeout(1800);
  for(const [width,height]of [[1440,900],[960,700]]){
    await page.setViewportSize({width,height});await settle();
    await check(`Responsive ${width}x${height}: main controls remain in viewport and clickable`,async()=>{const selectors=['[data-action="pause"]','[data-action="speed"][data-value="32"]','[data-action="settings"]','.faction-entry','[data-action="develop"]','[data-action="tab"][data-value="life"]','[data-action="follow"]','[data-action="overlay"][data-value="resources"]','[data-action="cinematic"]'];const boxes=[];for(const selector of selectors){const el=page.locator(selector).first();const b=await el.boundingBox();assert.ok(b&&b.x>=0&&b.y>=0&&b.x+b.width<=width+1&&b.y+b.height<=height+1,`${selector} clipped: ${JSON.stringify(b)}`);await el.click({trial:true});boxes.push({selector,...b});}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);report.responsive.push({width,height,boxes});return {controls:boxes.length};});
    await shot(`responsive-${width}x${height}`);
  }
  await mobileControls();
  await check('No runtime errors through observer workflow',async()=>{assert.deepEqual(report.errors,[]);});
}catch(error){report.fatal=error.stack;console.error(error);}
finally{
  report.passed=report.checks.filter(c=>c.status==='passed').length;report.failed=report.checks.filter(c=>c.status==='failed').length;
  report.status=report.fatal?'aborted':'completed';await save(config,'controls-v2-report.json',report);console.log(JSON.stringify({passed:report.passed,failed:report.failed,fatal:report.fatal,report:output(config,'controls-v2-report.json')}));await browser?.close();
}
if(report.failed||report.fatal)process.exitCode=1;
