import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';

// Observer commands are real DOM/mouse/keyboard interactions. evaluate() reads
// state or projects world objects for mouse picking. Only the short deterministic
// replay test invokes step(); Developed world itself is exercised by a UI click.
const browser = await chromium.launch({channel:'chrome',headless:true});
const page = await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
page.setDefaultTimeout(9000);
const report={at:new Date().toISOString(),url:'http://127.0.0.1:4174/?seed=first-light',browser:'Local installed headless Chrome; not foreground performance evidence',checks:[],errors:[],warnings:[],screenshots:[],responsive:[]};
page.on('pageerror',e=>report.errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());if(m.type()==='warning')report.warnings.push(m.text());});
const button=(action,value)=>page.locator(`[data-action="${action}"]${value===undefined?'':`[data-value="${value}"]`}`);
const state=()=>page.evaluate(()=>({tick:littleworld.state.tick,step:littleworld.state.step,time:littleworld.state.time,seed:littleworld.state.seed,view:{...littleworld.view}}));
const settle=()=>page.waitForTimeout(500);
async function check(name,fn){try{const detail=await fn();report.checks.push({name,status:'passed',detail});console.log(`PASS ${name}`);}catch(error){report.checks.push({name,status:'failed',error:error.message});console.log(`FAIL ${name}: ${error.message}`);}report.passed=report.checks.filter(c=>c.status==='passed').length;report.failed=report.checks.filter(c=>c.status==='failed').length;await writeFile('screenshots/controls-v2-report.json',JSON.stringify({...report,status:'in-progress'},null,2));}
async function pause(){if(!(await state()).view.paused)await button('pause').click();await settle();}
async function settings(){if(!await page.locator('#atlas-settings').isVisible())await button('settings').click();}
async function reset(seed){await pause();await settings();await page.locator('#atlas-seed').fill(seed);await page.locator('.seed-form button[type="submit"]').click();await settle();}
async function select(id){await page.locator(`.faction-list [data-value="${id}"]`).click();await settle();}
async function shot(name){const path=`screenshots/controls-v2-${name}.png`;await page.screenshot({path});report.screenshots.push({path,...await page.evaluate(()=>({tick:littleworld.state.tick,seed:littleworld.state.seed,viewport:{width:innerWidth,height:innerHeight},camera:littleworld.camera.position.toArray(),target:littleworld.controls.target.toArray(),diagnostics:littleworld.diagnostics}))});}
async function populationEvidence(){return page.evaluate(()=>{const d=littleworld.diagnostics;let actualInstances=0;const meshes=[];littleworld.scene.traverse(o=>{if(o.isInstancedMesh&&o.geometry?.attributes?.crowdMotion){actualInstances+=o.count;meshes.push({name:o.name,count:o.count,visible:o.visible});}});return {total:littleworld.state.settlements.reduce((n,s)=>n+s.population,0),diagnostics:d,actualInstances,meshes,scale:document.querySelector('[data-slot="world-scale"]').innerText};});}
await mkdir('screenshots',{recursive:true});
try{
  await page.goto(report.url);await page.waitForFunction(()=>window.littleworld);await pause();
  await check('Boot: six faction controls, WebGL canvas, current cycle labels',async()=>{assert.equal(await page.locator('.faction-entry').count(),6);assert.equal(await page.locator('#app canvas').count(),1);assert.match(await page.locator('.world-date').innerText(),/World cycle/i);assert.doesNotMatch(await page.locator('#ui').innerText(),/\bday(?:s)?\b/i);return page.evaluate(()=>{const gl=littleworld.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),initialPopulation:littleworld.diagnostics.totalPopulation};});});
  await check('Pause button freezes cycles, pulses, and sampled individual motion',async()=>{const a=await state();const motion=await page.evaluate(()=>littleworld.getMotionSamples());await page.waitForTimeout(1100);const b=await state();assert.equal(b.step,a.step);assert.equal(b.time,a.time);assert.deepEqual(await page.evaluate(()=>littleworld.getMotionSamples()),motion);assert.equal(await button('pause').getAttribute('aria-label'),'Resume simulation');return {step:b.step,samples:motion.length};});
  await check('Resume button advances simulation pulses',async()=>{const a=await state();await button('pause').click();await page.waitForTimeout(1300);assert.ok((await state()).step>a.step);await pause();});
  for(const speed of [1,4,16,32])await check(`${speed}x button sets speed, resumes, and advances cycles`,async()=>{await button('speed',speed).click();const a=await state();assert.equal(a.view.speed,speed);assert.equal(a.view.paused,false);assert.equal(await button('speed',speed).getAttribute('aria-pressed'),'true');await page.waitForTimeout(1100);const b=await state();assert.ok(b.step>a.step);await pause();return {pulses:b.step-a.step,cycles:b.time-a.time};});
  await check('Space toggles pause; number shortcuts choose all four rates',async()=>{await page.locator('#app canvas').focus();await page.keyboard.press('Space');assert.equal((await state()).view.paused,false);await page.keyboard.press('Space');assert.equal((await state()).view.paused,true);for(const [key,speed]of [['1',1],['2',4],['3',16],['4',32]]){await page.keyboard.press(key);assert.equal((await state()).view.speed,speed);}await pause();});
  await reset('first-light');
  await check('Seed form resets to cycle zero and clears selection follow',async()=>{const s=await state();assert.equal(s.seed,'first-light');assert.equal(s.tick,0);assert.equal(s.step,0);assert.equal(s.view.selectedId,'s0');assert.equal(s.view.followId,null);});
  await check('Seed input protects text from global keyboard shortcuts',async()=>{await settings();const a=await state();await page.locator('#atlas-seed').fill('');await page.locator('#atlas-seed').pressSequentially('1 2 3 4 f c h');const b=await state();assert.equal(b.view.speed,a.view.speed);assert.equal(b.view.paused,a.view.paused);assert.equal(b.view.cinematic,a.view.cinematic);assert.equal(await page.locator('#atlas-seed').inputValue(),'1 2 3 4 f c h');await page.keyboard.press('Escape');});
  await check('Reset same seed reproduces identical initial state and 30-cycle replay',async()=>{await reset('controls-determinism');const a=await page.evaluate(()=>JSON.stringify(littleworld.state));await page.evaluate(()=>littleworld.step(30));const b=await page.evaluate(()=>JSON.stringify(littleworld.state));await reset('controls-determinism');assert.equal(await page.evaluate(()=>JSON.stringify(littleworld.state)),a);await page.evaluate(()=>littleworld.step(30));assert.equal(await page.evaluate(()=>JSON.stringify(littleworld.state)),b);return {initialBytes:a.length,replayBytes:b.length};});
  await reset('first-light');
  for(let i=0;i<6;i++)await check(`Faction ${i+1} click selects actual colony`,async()=>{await select(`s${i}`);assert.equal((await state()).view.selectedId,`s${i}`);assert.equal(await page.locator(`.faction-list [data-value="s${i}"]`).getAttribute('aria-pressed'),'true');return page.locator('.selection-header').innerText();});
  await check('Visible world label selects the named settlement',async()=>{let clicked=false;const labels=page.locator('.world-label');for(let i=0;i<await labels.count();i++){const label=labels.nth(i);if(!await label.isVisible())continue;try{await label.click({trial:true,timeout:600});}catch{continue;}const name=await label.innerText();await label.click();const id=await page.evaluate(name=>littleworld.state.settlements.find(s=>s.name===name)?.id,name);assert.equal((await state()).view.selectedId,id);clicked=true;break;}assert.ok(clicked,'No unobscured world label available');});
  await check('Follow button focuses colony and toggles off',async()=>{await select('s0');const a=await page.evaluate(()=>littleworld.camera.position.toArray());await button('follow').click();await page.waitForTimeout(1000);assert.equal((await state()).view.followId,'s0');assert.equal(await button('follow').getAttribute('aria-pressed'),'true');assert.notDeepEqual(await page.evaluate(()=>littleworld.camera.position.toArray()),a);await button('follow').click();assert.equal((await state()).view.followId,null);});
  await check('World drag cancels follow',async()=>{await button('follow').click();await settle();await page.mouse.move(650,450);await page.mouse.down();await page.mouse.move(735,430,{steps:7});await page.mouse.up();assert.equal((await state()).view.followId,null);});
  await check('Cinematic button moves paused camera; Escape exits',async()=>{await button('cinematic').click();const a=await page.evaluate(()=>littleworld.camera.position.toArray());await page.waitForTimeout(1000);assert.equal((await state()).view.cinematic,true);assert.notDeepEqual(await page.evaluate(()=>littleworld.camera.position.toArray()),a);await page.keyboard.press('Escape');await settle();assert.equal((await state()).view.cinematic,false);assert.equal((await state()).view.followId,null);});
  await check('Keyboard F/C/H follow, cinematic and UI visibility controls work',async()=>{await page.locator('#app canvas').focus();await page.keyboard.press('f');assert.equal((await state()).view.followId,(await state()).view.selectedId);await page.keyboard.press('c');assert.equal((await state()).view.cinematic,true);await page.keyboard.press('c');assert.equal((await state()).view.cinematic,false);await page.keyboard.press('h');assert.equal(await page.locator('#ui').isVisible(),false);await page.keyboard.press('h');assert.equal(await page.locator('#ui').isVisible(),true);await page.keyboard.press('Escape');});
  await check('Settings quality switches real renderer shadows',async()=>{await settings();assert.equal(await button('settings').getAttribute('aria-expanded'),'true');await page.locator('#atlas-quality').selectOption('low');assert.equal((await state()).view.quality,'low');assert.equal(await page.evaluate(()=>littleworld.renderer.shadowMap.enabled),false);await page.locator('#atlas-quality').selectOption('high');assert.equal((await state()).view.quality,'high');assert.equal(await page.evaluate(()=>littleworld.renderer.shadowMap.enabled),true);});
  await check('Field guide opens and explains actual individuals and cycle time',async()=>{await page.locator('.render-reading [data-action="help"]').click();assert.ok(await page.locator('.field-guide').isVisible());assert.equal(await page.locator('#atlas-settings').isVisible(),false);const guide=await page.locator('.field-guide').innerText();assert.match(guide,/actual individual/i);assert.match(guide,/cycle is one simulation second/i);await page.locator('.guide-close').click();assert.equal(await page.locator('.field-guide').isVisible(),false);});
  await reset('first-light');await page.keyboard.press('Escape');await page.waitForTimeout(1700);await shot('initial-1440');
  await check('Developed world button actually advances current seed by 1,200 cycles',async()=>{const a=await state();const started=Date.now();await button('develop').click();await page.waitForFunction(()=>littleworld.view.advancing===null&&littleworld.state.tick>=1200,{},{timeout:180000});await settle();const b=await state();assert.equal(b.seed,a.seed);assert.equal(b.tick-a.tick,1200);assert.equal(b.step-a.step,12000);assert.equal(b.view.paused,true);assert.equal(await button('develop').isEnabled(),true);assert.equal(await button('develop').getAttribute('aria-busy'),'false');assert.match(await page.locator('.ui-toast').innerText(),/1,200 cycles simulated/);return {milliseconds:Date.now()-started,cycle:b.tick};});
  await check('Developed world population equals represented and real visible mesh instances',async()=>{const e=await populationEvidence();report.populationEvidence=e;assert.equal(e.diagnostics.crowds.representedIndividuals,e.total);assert.equal(e.diagnostics.crowds.visibleIndividuals+e.diagnostics.crowds.culledIndividuals,e.total);assert.equal(e.actualInstances,e.diagnostics.crowds.visibleIndividuals);assert.equal(e.diagnostics.crowds.populationAccountingDelta,0);assert.match(e.scale,new RegExp(e.total.toLocaleString('en')));return {population:e.total,represented:e.diagnostics.crowds.representedIndividuals,visible:e.diagnostics.crowds.visibleIndividuals,actualMeshInstances:e.actualInstances};});
  await check('Population and visible counts in diagnostics settings are truthful',async()=>{await button('diagnostics').click();const e=await populationEvidence();const rows=await page.locator('.render-counts > div').evaluateAll(rows=>Object.fromEntries(rows.map(r=>[r.querySelector('dt').textContent,r.querySelector('dd').textContent])));assert.equal(rows['Actual population'],e.total.toLocaleString('en'));assert.equal(rows['Represented individuals'],e.diagnostics.crowds.representedIndividuals.toLocaleString('en'));assert.equal(rows['Visible in this view'],e.diagnostics.crowds.visibleIndividuals.toLocaleString('en'));await button('settings').click();return rows;});
  for(const mode of ['territory','knowledge','routes','resources','none'])await check(`${mode} overlay click updates view and accessible state`,async()=>{await button('overlay',mode).click();await settle();assert.equal((await state()).view.overlay,mode);assert.equal(await button('overlay',mode).getAttribute('aria-pressed'),'true');return page.evaluate(()=>({calls:littleworld.diagnostics.drawCalls,triangles:littleworld.diagnostics.triangles,groups:littleworld.state.groups.length}));});
  await shot('developed-1440');
  await check('Life, Intelligence, Record tabs update accessible panel',async()=>{for(const tab of ['intelligence','record','life']){await button('tab',tab).click();assert.equal(await button('tab',tab).getAttribute('aria-selected'),'true');assert.equal(await page.locator('[role="tabpanel"]').getAttribute('aria-labelledby'),`atlas-tab-${tab}`);assert.ok((await page.locator('[role="tabpanel"]').innerText()).length>30);}});
  await check('Inspector tabs support arrow, Home, and End keys',async()=>{await button('tab','life').focus();for(const[key,tab]of [['ArrowRight','intelligence'],['End','record'],['Home','life'],['ArrowLeft','record']]){await page.keyboard.press(key);assert.equal(await button('tab',tab).getAttribute('aria-selected'),'true');}await button('tab','life').click();});
  await check('Chronicle scope switches world and selected faction events',async()=>{await button('scope').click();assert.equal(await button('scope').innerText(),'Selected');await button('scope').click();assert.equal(await button('scope').innerText(),'All life');});
  await check('Visible party control selects and follows actual group',async()=>{await select('s0');await button('tab','life').click();const party=page.locator('.active-parties button').first();assert.ok(await party.count());const id=await party.getAttribute('data-value');await party.click();await settle();assert.equal((await state()).view.selectedId,id);assert.ok(await page.locator('.party-detail').isVisible());await button('follow').click();assert.equal((await state()).view.followId,id);await settle();await shot('party');await button('follow').click();return {id};});
  await check('Worksite link opens resource inspector and real remaining stock',async()=>{await select('s0');await button('tab','life').click();const site=page.locator('.site-links button').first();assert.ok(await site.count());const id=await site.getAttribute('data-value');await site.click();await settle();assert.equal((await state()).view.selectedId,id);assert.equal(await button('tab','life').innerText(),'Site');const node=await page.evaluate(id=>littleworld.state.nodes.find(n=>n.id===id),id);assert.match(await page.locator('.resource-introduction').innerText(),new RegExp(Math.round(node.amount).toLocaleString('en')));await button('follow').click();assert.equal((await state()).view.followId,id);await settle();await shot('resource');await button('follow').click();return {id,amount:node.amount};});
  await check('Resource Teams and Ledger tabs disclose actual teams and ledger values',async()=>{const id=(await state()).view.selectedId;const evidence=await page.evaluate(id=>{const node=littleworld.state.nodes.find(n=>n.id===id);return {teams:littleworld.state.groups.filter(g=>g.kind==='worker'&&g.targetId===id).length,ledger:littleworld.state.resourceLedger[node.kind]};},id);await button('tab','intelligence').click();assert.equal(await page.locator('.resource-teams > button').count(),evidence.teams);await button('tab','record').click();const dd=await page.locator('.ledger-list dd').allTextContents();assert.equal(dd[2],Math.round(evidence.ledger.extracted).toLocaleString('en'));assert.equal(dd[3],Math.round(evidence.ledger.delivered).toLocaleString('en'));await button('tab','life').click();return evidence;});
  await check('Canvas resource picking selects an actual visible deposit',async()=>{await page.keyboard.press('Escape');await page.waitForTimeout(1800);const points=await page.evaluate(async()=>{const {heightAt}=await import('/src/world.js');return littleworld.state.nodes.map(n=>{const p=littleworld.camera.position.clone().set(n.x,heightAt(n.x,n.z,littleworld.state.seed)+.4,n.z).project(littleworld.camera);const x=(p.x*.5+.5)*innerWidth,y=(-p.y*.5+.5)*innerHeight;return {id:n.id,x,y,z:p.z,clear:document.elementFromPoint(x,y)?.tagName==='CANVAS'};}).filter(p=>p.clear&&p.z<1&&p.x>220&&p.x<innerWidth-330&&p.y>100&&p.y<innerHeight-100).slice(0,16);});assert.ok(points.length);let result=null;for(const p of points){await page.mouse.click(p.x,p.y);await settle();const id=(await state()).view.selectedId;const node=await page.evaluate(id=>littleworld.state.nodes.find(n=>n.id===id),id);if(node){result={expected:p.id,selected:id,x:p.x,y:p.y};break;}}assert.ok(result,'All visible deposit canvas clicks failed to select any resource');return result;});
  await select('s0');await button('tab','life').click();await page.keyboard.press('Escape');await page.waitForTimeout(1800);
  for(const [width,height]of [[1440,900],[960,700]]){
    await page.setViewportSize({width,height});await settle();
    await check(`Responsive ${width}x${height}: main controls remain in viewport and clickable`,async()=>{const selectors=['[data-action="pause"]','[data-action="speed"][data-value="32"]','[data-action="settings"]','.faction-entry','[data-action="develop"]','[data-action="tab"][data-value="life"]','[data-action="follow"]','[data-action="overlay"][data-value="resources"]','[data-action="cinematic"]'];const boxes=[];for(const selector of selectors){const el=page.locator(selector).first();const b=await el.boundingBox();assert.ok(b&&b.x>=0&&b.y>=0&&b.x+b.width<=width+1&&b.y+b.height<=height+1,`${selector} clipped: ${JSON.stringify(b)}`);await el.click({trial:true});boxes.push({selector,...b});}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);report.responsive.push({width,height,boxes});return {controls:boxes.length};});
    await shot(`responsive-${width}x${height}`);
  }
  await check('No runtime errors through observer workflow',async()=>{assert.deepEqual(report.errors,[]);});
}catch(error){report.fatal=error.stack;console.error(error);}
finally{
  report.passed=report.checks.filter(c=>c.status==='passed').length;report.failed=report.checks.filter(c=>c.status==='failed').length;
  report.status=report.fatal?'aborted':'completed';await writeFile('screenshots/controls-v2-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed,fatal:report.fatal,report:'screenshots/controls-v2-report.json'}));await browser.close();
}
if(report.failed||report.fatal)process.exitCode=1;
